"""add_delivery_otp_to_orders

Revision ID: 935a17811cce
Revises: 93a188000660
Create Date: 2026-01-11 19:34:17.138917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935a17811cce'
down_revision: Union[str, None] = '93a188000660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_otp', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_orders_delivery_otp'), 'orders', ['delivery_otp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_delivery_otp'), table_name='orders')
    op.drop_column('orders', 'delivery_otp')
    # ### end Alembic commands ###

