"""add_delivery_history_table

Revision ID: 93a188000660
Revises: d6575a3085e7
Create Date: 2026-01-11 19:19:11.267711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '93a188000660'
down_revision: Union[str, None] = 'd6575a3085e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('delivery_partner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='deliveryattemptstatus', native_enum=False, length=20), nullable=False),
    sa.Column('is_cod', sa.Boolean(), nullable=False),
    sa.Column('cod_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cod_collected', sa.Boolean(), nullable=True),
    sa.Column('cod_collected_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Enum('CUSTOMER_NOT_AVAILABLE', 'WRONG_ADDRESS', 'CUSTOMER_REFUSED', 'DAMAGED_PACKAGE', 'OTHER', name='deliveryfailurereason', native_enum=False, length=50), nullable=True),
    sa.Column('failure_notes', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_time_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_partner_id'], ['delivery_partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_history_delivery_partner_id'), 'delivery_history', ['delivery_partner_id'], unique=False)
    op.create_index(op.f('ix_delivery_history_order_id'), 'delivery_history', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_history_order_id'), table_name='delivery_history')
    op.drop_index(op.f('ix_delivery_history_delivery_partner_id'), table_name='delivery_history')
    op.drop_table('delivery_history')
    # ### end Alembic commands ###

