"""add_category_attributes_and_product_attribute_values

Revision ID: 95cde7396ba0
Revises: 167153bf2133
Create Date: 2026-01-10 22:26:23.906205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '95cde7396ba0'
down_revision: Union[str, None] = '167153bf2133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_attributes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attribute_type', sa.Enum('TEXT', 'NUMBER', 'SELECT', 'MULTI_SELECT', 'BOOLEAN', name='attributetype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_inherited', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('show_in_listing', sa.Boolean(), nullable=False),
    sa.Column('show_in_details', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_attributes_category_id'), 'category_attributes', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_attributes_slug'), 'category_attributes', ['slug'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attribute_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['category_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_attribute_values_attribute_id'), 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_product_id'), 'product_attribute_values', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_attribute_values_product_id'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_attribute_id'), table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_category_attributes_slug'), table_name='category_attributes')
    op.drop_index(op.f('ix_category_attributes_category_id'), table_name='category_attributes')
    op.drop_table('category_attributes')
    # Drop enum type
    sa.Enum('TEXT', 'NUMBER', 'SELECT', 'MULTI_SELECT', 'BOOLEAN', name='attributetype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
