"""add_payments_and_payment_logs_tables

Revision ID: f3b0ee454491
Revises: 95cde7396ba0
Create Date: 2026-01-11 14:50:37.441469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid


# revision identifiers, used by Alembic.
revision: str = 'f3b0ee454491'
down_revision: Union[str, None] = '95cde7396ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new values to existing PaymentStatus enum (it already exists from Order model)
    conn = op.get_bind()
    if conn is not None:
        # Check and add new enum values if they don't exist
        new_values = ['CREATED', 'AUTHORIZED', 'CAPTURED']
        for value in new_values:
            try:
                result = conn.execute(sa.text(
                    f"SELECT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = '{value}' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'paymentstatus'))"
                )).scalar()
                if not result:
                    conn.execute(sa.text(f"ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS '{value}'"))
            except Exception:
                # If enum value already exists or other error, continue
                pass
    
    # Use existing PaymentStatus enum
    payment_status_enum = postgresql.ENUM(
        'PENDING', 'CREATED', 'AUTHORIZED', 'CAPTURED', 'PAID', 'FAILED', 'REFUNDED',
        name='paymentstatus',
        create_type=False
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False, server_default='INR'),
    sa.Column('status', payment_status_enum, nullable=False, server_default='PENDING'),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
    sa.Column('payment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_logs_event_type'), 'payment_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_logs_payment_id'), 'payment_logs', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_logs_payment_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_event_type'), table_name='payment_logs')
    op.drop_table('payment_logs')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    # Drop enum
    sa.Enum(name='paymentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

