"""
Pydantic Schemas
Request/Response models for API validation
"""

from app.schemas.user import (
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
    Token,
    TokenPayload,
    RefreshTokenRequest,
    PasswordChange,
    MessageResponse,
)
from app.schemas.vendor import (
    VendorCreate,
    VendorUpdate,
    VendorResponse,
    VendorPublicResponse,
    VendorListResponse,
    VendorAdminResponse,
    VendorApproval,
    VendorSuspend,
)
from app.schemas.category import (
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    CategoryTreeNode,
    CategoryListResponse,
    CategoryTreeResponse,
    CategoryBreadcrumb,
    CategoryWithBreadcrumb,
)
from app.schemas.service_zone import (
    ServiceZoneCreate,
    ServiceZoneUpdate,
    ServiceZoneResponse,
    ServiceZoneListResponse,
    DeliveryCheckRequest,
    DeliveryCheckResponse,
)
from app.schemas.product import (
    ProductCreate,
    ProductUpdate,
    ProductResponse,
    ProductPublicResponse,
    ProductListResponse,
    ProductVendorListResponse,
    ProductCard,
    ProductFilters,
    SellUnitCreate,
    SellUnitUpdate,
    SellUnitResponse,
    ProductImageCreate,
    ProductImageResponse,
    ProductImageReorder,
    InventoryCreate,
    InventoryUpdate,
    InventoryResponse,
    StockAdjustment,
)
from app.schemas.address import (
    AddressCreate,
    AddressUpdate,
    AddressResponse,
    AddressListResponse,
)
from app.schemas.cart import (
    CartItemAdd,
    CartItemUpdate,
    CartItemProduct,
    CartItemResponse,
    CartResponse,
    CartSummary,
)
from app.schemas.order import (
    OrderCreate,
    OrderStatusUpdate,
    OrderCancel,
    OrderItemResponse,
    OrderVendorInfo,
    OrderAddressSnapshot,
    OrderResponse,
    OrderListResponse,
    OrderBriefResponse,
    VendorOrderResponse,
    VendorOrderListResponse,
    StockReservationResponse,
)
from app.schemas.attribute import (
    CategoryAttributeCreate,
    CategoryAttributeUpdate,
    CategoryAttributeResponse,
    CategoryAttributeListResponse,
    ProductAttributeValueCreate,
    ProductAttributeValueUpdate,
    ProductAttributeValueResponse,
    ProductAttributeValueWithDetails,
    BulkProductAttributeValues,
    AttributeFilter,
    AttributeFilterRequest,
    AttributeFilterOption,
    AttributeFilterGroup,
    CategoryFilterOptions,
)
from app.schemas.payment import (
    PaymentCreate,
    PaymentResponse,
    PaymentVerify,
    PaymentCreateOrderResponse,
    PaymentStatusResponse,
    PaymentLogResponse,
    PaymentListResponse,
    PaymentRefundRequest,
    PaymentRefundResponse,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "Token",
    "TokenPayload",
    "RefreshTokenRequest",
    "PasswordChange",
    "MessageResponse",
    # Vendor schemas
    "VendorCreate",
    "VendorUpdate",
    "VendorResponse",
    "VendorPublicResponse",
    "VendorListResponse",
    "VendorAdminResponse",
    "VendorApproval",
    "VendorSuspend",
    # Category schemas
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "CategoryTreeNode",
    "CategoryListResponse",
    "CategoryTreeResponse",
    "CategoryBreadcrumb",
    "CategoryWithBreadcrumb",
    # Service zone schemas
    "ServiceZoneCreate",
    "ServiceZoneUpdate",
    "ServiceZoneResponse",
    "ServiceZoneListResponse",
    "DeliveryCheckRequest",
    "DeliveryCheckResponse",
    # Product schemas
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductPublicResponse",
    "ProductListResponse",
    "ProductVendorListResponse",
    "ProductCard",
    "ProductFilters",
    "SellUnitCreate",
    "SellUnitUpdate",
    "SellUnitResponse",
    "ProductImageCreate",
    "ProductImageResponse",
    "ProductImageReorder",
    "InventoryCreate",
    "InventoryUpdate",
    "InventoryResponse",
    "StockAdjustment",
    # Address schemas
    "AddressCreate",
    "AddressUpdate",
    "AddressResponse",
    "AddressListResponse",
    # Cart schemas
    "CartItemAdd",
    "CartItemUpdate",
    "CartItemProduct",
    "CartItemResponse",
    "CartResponse",
    "CartSummary",
    # Order schemas
    "OrderCreate",
    "OrderStatusUpdate",
    "OrderCancel",
    "OrderItemResponse",
    "OrderVendorInfo",
    "OrderAddressSnapshot",
    "OrderResponse",
    "OrderListResponse",
    "OrderBriefResponse",
    "VendorOrderResponse",
    "VendorOrderListResponse",
    "StockReservationResponse",
    # Attribute schemas
    "CategoryAttributeCreate",
    "CategoryAttributeUpdate",
    "CategoryAttributeResponse",
    "CategoryAttributeListResponse",
    "ProductAttributeValueCreate",
    "ProductAttributeValueUpdate",
    "ProductAttributeValueResponse",
    "ProductAttributeValueWithDetails",
    "BulkProductAttributeValues",
    "AttributeFilter",
    "AttributeFilterRequest",
    "AttributeFilterOption",
    "AttributeFilterGroup",
    "CategoryFilterOptions",
    # Payment schemas
    "PaymentCreate",
    "PaymentResponse",
    "PaymentVerify",
    "PaymentCreateOrderResponse",
    "PaymentStatusResponse",
    "PaymentLogResponse",
    "PaymentListResponse",
    "PaymentRefundRequest",
    "PaymentRefundResponse",
]
